### ISSUE TITLE
IronList Component

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#2556]
When listing data I want a generic Component repeater backed by a DataProvider so that I can use a consistent API for data fetching and infinite scrolling. Use case for a GitHub-like issue list:

```java
DataProvider<Issue> dp = IssueDataProvider.instance();
Repeater<IssueListItem> repeater = new Repeater<>();
repeater.setDataProvider(dp);
repeater.setComponentProvider(IssueListItem::new);
```

**Comment by Legioth** [comment]
Prototype for integrating `<iron-list>` can be found in https://github.com/vaadin/flow/commit/045d5e47b1b5ffcf44631549f601c5409fffa097#diff-f72bb04f0740c1204d44bc8040282407.

In general, the approach is exactly the same as for `Grid`, except the set of columns is fixed (i.e. more similar to e.g. `ComboBox`). In practice, there might also be an option for a placeholder "column" that is rendered when data has not been lazy loaded.

**Comment by pleku** [comment]
Currently this _Epic_ has been split into the following issues:
- [ ] #2920 IronList component with text support
- [ ] #2921 IronList template renderer support
- [ ] #2922 IronList template renderer event support
- [ ] #2923 IronList component renderer support
- [ ] #2924 IronList placeholder item support
- [ ] #2931 Move IronList Component to its own repository
- [ ] #2932 Release IronList 1.0.0.alpha1

**Comment by pleku** [comment]
Issue moved to [vaadin/vaadin-iron-list-flow #2](https://github.com/vaadin/vaadin-iron-list-flow/issues/2) via [**ZenHub**](https://www.zenhub.com/)
