### ISSUE TITLE
Enable Flow applications to be embedded in non-Vaadin Web-Pages.

### ISSUE THREAD

**Issue by riandree** [vaadin/flow#4316]
In Vaadin 8 it was possible to embed Vaadin UIs into Web-Pages not generated by 
the vaadin-servlet (https://vaadin.com/docs/v8/framework/advanced/advanced-embedding.html).

This option currently not seems to be supported by Flow.

EDIT by @pleku - Issues for this Epic:
- [x] #4984 Basic Theme handling for Embedded Flow
- [x] #5005 WebComponent security
- [x] #5008 WebComponent handling in Production mode
- [x] #5048 DX testing Embedding Flow
- [x] #5061 SSWC+Push : pushUrl should be derived from service URL
- [x] #5070 Extend the automatic servlet initialisation to also work with WebComponents
- [x] vaadin/flow-and-components-documentation#410 Tutorial for replacing the owner form in Spring petclinic with embedding a Flow application
- [x] #5179 Update Embedding Flow app example (Petclinic) to use the new API
- [x] vaadin/flow-and-components-documentation#500 Update the embedding Flow tutorial
- [x] #5176 Refactor the Embedding Flow apps as a Web Component API to use the new exporter design
- [x] #5259 Embedded web components: implement the ability to push property updates to client
- [x] #4940 Replace the owners form in Spring Petclinic with a Flow SSWC
- [x] #5078 SPIKE: make a proposal that unifies the WebComponentProperty and @WebComponentMethod
- [x] #5079 SPIKE: use existing Flow API to modify embedded Flow application in DOM2
- [x] #5148 Further explore the example about embedding the owner form in Petclinic app using the web component exporter approach
- [x] #5149 Create an example on embedding a Calendar Flow application as a web component using the exporter approach
- [x] #5150 Create an example on embedding a Calendar Flow application as a web component using the WebComponent annotation
- [x] #4822 SPIKE: Investigate SSWC
- [x] #4916 Create WebComponent annotations
- [x] #4917 Create a WebComponentRegistry and population during ServletContext init
- [x] #4918 Create WebComponent handlers
- [x] #4919 Create WebComponentUI and WebComponentWrapper
- [x] #4920 Create a WebComponent html generator
- [x] #4921 Enable having the UI be another element than body
- [x] #5006 WebComponent server push
- [x] #5027 Client-side should be informed of server url for WebComponents3
- [x] vaadin/flow-and-components-documentation#411 General documentation about embedding flow applications / server-side web components2
- [x] #5342 export component as JsModule when running Flow in npm mode

**Comment by alejandro-du** [comment]
It would be useful if several Flow apps could be embedded in the same web page. This is a frequent requirement in microservices.

**Comment by pleku** [comment]
We have a working prototype of a solution for this, and are targeting Vaadin 13 beta1 (beginning of February 2019) to ship this in a stable Flow version.

**Comment by pleku** [comment]
### Acceptance Criteria
Use case:
- When building web apps, I want to embed a Flow application inside another _non-Flow_ app or static web page, because I don't want to rebuild the whole application with Flow but only a certain part of it, so that I can save time and still start using Flow_

There is a tutorial for _Embedding Flow Applications_ that shows as an example on how to embed a Flow  application into the [Spring petclinic](http://projects.spring.io/spring-petclinic/#quick-start) app and replace e.g. the owners table there with a Flow based `Grid`.
