### ISSUE TITLE
Support Polymer 3, npm and ES6 modules for Java projects

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#4561]
This is an epic that consists of subissues that bring Polymer 3, npm & ES6 modules support to Flow instead of Polymer 2, Bower/webjars and html imports.

- [x] #5032 npm based development mode for Flow
- [x] #5033 Automated development mode for npm
- [x] #5034 npm based production build for Flow

**Comment by pleku** [comment]
For clarity - at the moment this is not in plans for Vaadin 12 (December 2018) nor Vaadin 13 (March 2019). No certainty that it will be included in Vaadin 14 (June 2019) either, but that has not been planned yet and is still quite far (over six months).

**Comment by RaresI** [comment]
HTML Imports are scheduled for removal from Chrome 73, in April 2019 (https://www.chromestatus.com/feature/5144752345317376). According to caniuse.com at that moment there will be exactly no major browser with native support for HTML imports (https://caniuse.com/#search=html%20imp). That may break a number of things and possibly require updates to existing code.

**Comment by pleku** [comment]
> That may break a number of things and possibly require updates to existing code.

Actually no, things will just keep on working because of a Polyfill that is used instead. and has been used thus far in all other browsers except Chrome.

**Comment by Legioth** [comment]
The one situation where it might break is if someone has concluded that they only need to support Chrome, and therefore they have explicitly disabled the polyfills. There's still nothing we can really do about that, except maybe informing users.

**Comment by pleku** [comment]
>For clarity - at the moment this is not in plans for Vaadin 12 (December 2018) nor Vaadin 13 (March 2019). No certainty that it will be included in Vaadin 14 (June 2019) either, but that has not been planned yet and is still quite far (over six months).

Just as an update: npm, Polymer 3 and ES6 modules support is currently WIP and is targeted for V14. The plan is that the old mode (Webjars/bower) will also keep work on working, so doing migration with the provided tool is optional.
There is no consensus yet what is the default mode, but deviating from it will be possible by using a deployment configuration parameter like `productionMode`.

**Comment by pleku** [comment]
Migration tool to be finished during the platform beta period #5037.
