### ISSUE TITLE
Pluto Portlet support for Flow

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#4760]
**EDIT 2: this about Portlet support for Pluto, using Portlet 3.0 specification. Portlet 2.0 support for other portlets like Liferay and/or Websphere will require additional effort (#5815 #5816) **

Current scope:
- [x] Preparations for getting started with Pluto #6243 
- [x] Learn how to run integration tests with Pluto #6244 
- [x] Investigate differences between 3.0 and 2.0 spec vaadin/portlet-support#10
- [x] Investigate how to preserve portlet state on refreshes vaadin/portlet-support#11
- [x] Investigate how to create shared frontend resources bundle vaadin/portlet-support#12
- [x] Prototype Portlet Mode support with a demo vaadin/portlet-support#20
- [x] Investigate enabling PortletHub support automatically vaadin/portlet-support#30
- [x] Investigate & Demonstrate Portlet window state support vaadin/portlet-support#26 vaadin/portlet-support#27
- [x] Investigate IPC between Vaadin and non-Vaadin portlets vaadin/portlet-support#28
- [x] Vaadin Portlet API proposal vaadin/portlet-support#25
- [x] Address Book Portlet Demo vaadin/portlet-support#29
- [x] Create base starter for portlets #6345 
- [x] UI state is preserved on refresh #6373 
- [x] Portlet support for Upload component #6374
- [x] Multiple portlets on the same page from a single `.war` #6375
- [x] Support portlet modes: edit & help #6377
- [x] Portlet window mode support #6527
- [x] Inter Portlet Communication support #6378 
- [x] Support CDI on portlets out of the box vaadin/cdi#116

Maybe:
- [x] Automatic building of the frontend resources bundle #6376

**Comment by gaaroth** [comment]
Hi! I'm very interested in this argument, since I'd really like to use Flow to rapidly develop portlets in IBM Portal. I really don't like to fall back on Vaadin 8 for that. Any news on this front?
Thank you in advance!

**Comment by pleku** [comment]
Hi @gaaroth. The prerequisite for this is #4316 which is targeted for Vaadin 13. Portlet support would also require #3522 so that refreshes will not reset the UI state. This issue is mostly about adding back the `Portlet` specific APIs to the server side, but as there is much work to be done before that, early Q2 2019 (with Vaadin 14 release on June) is the earliest we can target the Portlet support at the moment. 

For anyone interested in Porlet support, it will help us prioritize the needed things for this if we get +1s for this issue and also the use cases for _why_ you specifically want to develop applications using Portlets. And we also appreciate to know which Portals you are targeting. Thanks

**Comment by gualtierotesta** [comment]
+1
We use Vaadin 7 and 8 on IBM WebSphere/Portal 8.5 and 9.0 and we are interested to migrate current applications and develop new ones on Vaadin 10+.
Reasons why we use Portal: many. For example, we use the Portal theme to give the user access (links) to other applications/resources while one application is shown in the page. We use Portal API to have a more generic/abstract user identity representation, regardless the underlying identity provider.

**Comment by larbigj** [comment]
+1 
We use Vaadin 7 on Liferay 6.2 and I like to use new features from latest vaadin / liferay.

**Comment by JaySunMoy** [comment]
+1

**Comment by n3phtys** [comment]
As a Liferay Dev I would love to be able to use Vaadin Flow for Portlet development. In this case it directly competes with JSF, which could be considered 'old'.
If Vaadin could enable this within 2019 I am pretty sure it will help Vaadin's adoption a lot. If not I'm afraid traditional SPA frameworks like Angular or react with REST backends will take too much of the cake that is rapid and compile-time-checked portlet development.

**Comment by Shimakuchi** [comment]
Hi 👋🏻 still develop Vaadin 8 portlets as I am a Liferay 7.1 user. I just read that Vaadin 12 (Flow) now supports OSGi. I am very interesstet to update vaadin. There are so much more, better and easier to use component. Have someone a working Liferay 7.1+Vaadin12+Gradle Example?

**Comment by pleku** [comment]
@Shimakuchi we are currently prototyping the Liferay 7.1 support (as portlets), which will need the embedding support (#4316) to be concluded before it will work properly.

It might be possible to _hack_ things to work before that, but I don't think that is a good solution to start building apps on top.

**Comment by stuartboulton** [comment]
+1
Hi - Currently considering to develop latest flow version that implements this spec against Liferay 7.1, 2-3rd quarter 2019.  We have V7 against Liferay 6.2 and V8 against Liferay 7.0.

**Comment by arcsinnovate** [comment]
+1
Hi, we are very much looking for this flow with portlet support. We are hooked to Liferay 7 but cannot wait to use Vaadin flow with it.

**Comment by donmarcoef** [comment]
+1

**Comment by supplier-tripleeye** [comment]
+1
Hi, we had to do a lot of time consuming extra work to get earlier versions of liferay/vaadin working together. With vaadin 8 and liferay 7 it finally worked out of the box. 
Now we need liferay portlet development in vaadin's lates version for a new liferay projet.

**Comment by pleku** [comment]
### A brief update here:
We are currently slowly working on Portlet 2.0 support for Vaadin. The work is ongoing and will not be available in 14.0. Our current target is to have some support level by Vaadin 15 for Portlet API 2.0. Currently we are using Liferay DXP 7.1 as the test portal but will try to make it work on top of Pluto which is the reference portal for Portlet 3.0 (JSR-362).

After 2.0 support we will continue with some Portlet 3.0 specific features for Pluto first (list not yet known), but we have the opportunity to later on to target specific 2.0 Portals like:
- Liferay DXP 7.1 #5815
- IBM Websphere Portal #5816

**Comment by daghosoft** [comment]
+1

**Comment by DanieleVistalli** [comment]
+1

**Comment by MarcoMerlo** [comment]
+1

**Comment by rlegorreta** [comment]
+1

**Comment by rlegorreta** [comment]
+1.
We urge to start a new Liferay 7.1 DXP project. We don't want to use Vaadin 8 but Flow.

**Comment by pleku** [comment]
Issue description updated with issues that are currently in scope.

**Comment by joheriks** [comment]
Portlet 1.0.0.beta1 release:
https://github.com/vaadin/portlet/releases/tag/1.0.0.beta1
