### ISSUE TITLE
npm based development mode for Flow

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#5032]
This is only for development mode, production mode is handled in another issue. For now we expect the user to have installed Java & Maven and node & npm install done. There either is a package.json file, or it is a very basic version is generated by us.

- [x] determine the npm mode
- [x] start webpack on `VaadinService` start up
- [x] add a request handler for proxying the frontend resource requests to webpack
- [x] create a new annotation `JsModule` to replace html imports
- [x] parse the template from the bundle to be able to do ID mapping
- [x] cache the template parsing results based on webpack hash/timestamp/whatnot
- [x] map from `@HtmlImport` to `@JsModule` when in npm mode as a temporary (?) solution
- [x] investigate where the stats.json file should be located
