### ISSUE TITLE
Automated configuration for development time

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#5033]
- [x] #5145 scan for `@JsModule` annotation from components on compile time
- [x] #5124 populate package.json based on the discovered modules, there is a plugin for automatically install automatically any missing modules that are encountered, it will by default update package.json but can be disabled
- [x] #5120 populate "main.js" based on the discovered modules
- [x] #5074  In development mode, it should be possible to use another theme than Lumo with @Theme
- [x] vaadin/beverage-starter-flow#295 add an option to trigger the annotation scanning on hot deploy for changed classes
component-starter-flow
- [ ] vaadin/component-starter-flow#51 Update the starter to be npm & p3 based
- [ ] vaadin/flow-and-components-documentation#498 Update the component starter documentation to be npm & p3 based instead of webjar based
- [x] vaadin/beverage-starter-flow#307 When pressing `ctrl-c` exec plugin outputs an error message in console
- [ ] vaadin/beverage-starter-flow#313 SPIKE: investigate whether to replace jetty with tomcat
