### ISSUE TITLE
npm based production build for Flow

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#5034]
- [x] in the beginning of the production build, populate a index.js that includes everything 
- [x] before packaging, run the webpack build to output the bundle to be included into the package
- [x] switch from using `frontend://` targeting `frontend-es5/` and `frontend-es6/` to adding two nice script imports for browsers that support either of those
- [x] update production build documentation [basic documentation](https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/production/tutorial-production-mode-basic.asciidoc)
- [x] update documentation on [how to customize the production bundle](https://github.com/vaadin/flow-and-components-documentation/tree/master/documentation/production) (using chunks?) 
- [x] update advanced / troubleshooting production build [documentation](https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/production/tutorial-production-mode-advanced.asciidoc)
- [x] update Bakery production bundling [configuration](https://github.com/vaadin/bakery-app-starter-flow-spring/blob/master/pom.xml#L262) and documentation 
- [x] update all (other) starters production build configuration
- [x] DX test production build experience
