### ISSUE TITLE
Frontend development tools should be automatically installed

### ISSUE THREAD

**Issue by mstahv** [vaadin/flow#6249]
Since Vaadin 14 build fails if npm is not installed. 

Many of our core audience are allergic to frontend development tools and have chosen Vaadin because they can ignore all that can build their web UI with plain Java tools. Thus we shouldn't nag about uninstalled npm, but just install it to project or to ~/.vaadin for them and give a warning that thing might be bit faster if it was installed locally.

Proofpoints can already be found on forum and SOF

**Comment by Artur-** [comment]
Is there any reason why we should not install it system wide in ~/.vaadin i.e. in the users homedir? This would install it only once and use it for all projects

**Comment by mstahv** [comment]
I can't think why we wouldn't do that.

**Comment by mstahv** [comment]
We must note that requiring npm installation makes also setting up CI more complicated. This is what I got when trying to GitHub actions for one of my projects:

    [ERROR] Could not get a response from '[/usr/local/bin/npm, -v]' command in 3 seconds

**Comment by mstahv** [comment]
Optimal solution for this would be that:

 * If Vaadin (development mode or production build) can't find a proper npm (not existing at all or wrong version), it automatically downloads one and uses it.
 * There is a setting that allow to force the behaviour.
 * npm is cached locally (e.g. in .vaadin directory as suggested by @Artur- 
 
For Gradle plugin there was a task introduced that one can call and which installs project global node/npm. That was already found helpful  by the community. If the optimal solution is found too hard, we could maybe implement just that. If not, then that feature probably becomes obsolete in the Gradle plugin as it will be implemented by Vaadin development mode helpers already 🤔 Please share your ideas @vaadin/flow

**Comment by mstahv** [comment]
@samie This is one of your favourite topics, any insights how this should work?

**Comment by jhult** [comment]
Just to confirm, for Vaadin 14, this would use npm, and for Vaadin 15, it would use pnpm? Or do you just want to jump directly to pnpm?

**Comment by mstahv** [comment]
pnpm would be an implementation detail. IIRC, we already install it automatically if it is not installed. Why did you ask? Do you have some concerns or issues with pnpm?

**Comment by jhult** [comment]
I just wanted to make sure that you wouldn't need to do re-work when eventually switching to pnpm.

:)

**Comment by pleku** [comment]
To clarify, this will be targeted to 14.2, but it will be done to master branch (3.x).

### Acceptance Criteria
- [ ] Existing 14 projects should work as is, regardless of having local or global installation of node.
- [ ] New users who don't have node.js installed, do not have to do anything to get a Vaadin project up and running. Tested with vanilla skeleton and spring skeleton projects in:
     - [ ] Windows 10
     - [ ] MacOS Catalina & Mojave
     - [ ] Linux (Ubuntu & Fedora)
- [ ] If 1) project local or 2) global node is installed, then those are used to keep existing projects unaffected, and `.vaadin` is the 3) priority option
- [ ] The logs should mention that node.js was installed to `.vaadin` in home folder
- [ ] If we discover an older Node.js from project local or global installation, we don't automatically install a new version, but fail with a clear error message
- [ ] Add a configuration for explicitly installing a node.js to `.vaadin`, regardless of what is installed globally
- [ ] There should be a log message stating the path where node.js is used (both making production build and starting app in devmode)
- [ ] This should be done for all `prepare-frontend`, `build-frontend` and when starting application (spring boot case)
- [ ] Test automatic installation with Travis for `build-frontend`
- [ ] Revise the documentation for V15 about node.js requirement
- [ ] Revise the documentation for V14.2 about node.js requirement
- [ ] Breach all the silos that need to know about this change for the workflow (tutorials, DX testing)

**Comment by knoobie** [comment]
Please add "Running CI behind a proxy (allow for configuration of a proxy)" as Acceptance Criteria. It's common practice and should not be missed if possible. 

Example: all our Jenkins builds run within the companies network and have to access one global artifactory where all binaries / artefacts are stored without any direct access to the internet (Security Reasons / Government Regulation)

**Comment by pleku** [comment]
@knoobie the configuration for proxies was done separately as in #7567, it would be great if you could please test it when it lands soon to 14.2.0.alpha5, thanks.
