### ISSUE TITLE
Frontend resources bundle for multiple Vaadin micro frontends (or Portlets) in different wars 

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#6376]
_When having multiple Vaadin portlets on the same page, I want to be able to easily build a shared frontend resources bundle for the portlets when they are inside different war files, so that I can build and deploy updated portlets easily_

Continuation for #6375

### Acceptance Criteria
- [x] #6922 
- [x] #6923 
- [x] The addressbook-portlet demo is an example project with multiple modules and `.war` files available vaadin/portlet-support#84
- [x] vaadin/portlet-support#122
- [x] vaadin/portlet-support#123
- [x] vaadin/portlet-support#124
- [x] new prereleases of Flow 2.2
