### ISSUE TITLE
Import basic types (string/integer/double/boolean) into a template model

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#730]
TemplateModel should contain a static helper method for importing beans or parts of beans into the model, Importing means copying the values from the bean. There is no connection between the bean and the model after the import.

The properties are copied using the property name in the bean, i.e. a `String getFirstName()` property is copied into "firstName" in the model.

The API should be

``` java
interface TemplateModel {

/**
 * Imports (copies) the properties from the bean and any sub beans into the model. The properties are found through introspection of the bean and are imported into the part of the model specified through <code>modelPath</code> or into the root model if <code>modelPath</code> is <code>""</code>. Each property is passed through the <code>filter</code> which can decide whether the property should be copied into the model or not.
**/
default void TemplateModel.import(Object bean, String modelPath, Predicate<String> filter)

/** 
 * Imports (copies) all properties from the bean and any sub beans into the model into the given part of the model. 
* @see import(Object,String,Predicate)
*/
default void TemplateModel.import(Object bean, String modelPath)

/**
 * Imports (copies) all properties from the bean and any sub beans into the model. 
* @see import(Object,String)
*/
default void TemplateModel.import(Object bean)
}
```

Depends on #729

Split into subtasks:
- [x] Import basic types from Bean to model #877
- [ ] Import sub Bean properties into model #880
- [ ] Import Bean properties into specific model path #878
- [ ] Import Bean properties passing filter to model path #879
